name: linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [clang, gcc]
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Install dependencies
      run: |
          sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Configure GameMath
      run: |
        cmake --preset ${{ matrix.platform }}
        
    - name: Build GameMath
      run: |
        cmake --build build
